# Stand-alone directories

SRC_DIR := src
OBJ_DIR := obj
INCLUDE_DIRS := ../include ../include/kernel ./include

# MOD_OBJ - Module Object. Its name will be the same as the module so it is
# a good idea to automate that.

CURR_DIR = $(notdir $(shell pwd))
MOD_OBJ := $(CURR_DIR).o

# Library dependencies

LIB_INCLUDE_DIRS := ../lib/include 

# Module sources and their object files

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ := $(SRC:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)

# Compiler settings

HFLAGS = -MMD 
CFLAGS+=-c

# Include directories

INCFLAGS = $(foreach TMP, $(LIB_INCLUDE_DIRS), -I$(TMP))
INCFLAGS += $(foreach TMP, $(INCLUDE_DIRS), -I$(TMP))

.PHONY: all clean

all: $(MOD_OBJ) 

$(MOD_OBJ): $(OBJ) | $(MOBJ_DIR)
	$(AR) rcs $@ $(OBJ) 

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $< -o $@ $(CFLAGS) $(HFLAGS) $(INCFLAGS) 

$(OBJ_DIR) $(MOBJ_DIR):
	mkdir -p $@

clean:
	@$(RM) -rv $(OBJ_DIR) $(MOBJ_DIR) 

-include $(OBJ:.o=.d)
