# Upper directories

ROOT_DIR := ../../
MODULES_DIR := ../

# Stand-alone directories

SRC_DIR := src/
OBJ_DIR := obj/
INC_DIR := $(MODULES_DIR)/include/ ./include/
MOBJ_DIR := mobj/

# MOD_OBJ - Module Object. Its name will be the same as the module so it is
# a good idea to automate that.

CURR_DIR = $(notdir $(shell pwd))
MOD_OBJ := $(MOBJ_DIR)/$(CURR_DIR).o

# Library dependencies

LIB_INC_DIR := $(ROOT_DIR)/lib/include

# Module sources and their object files

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ := $(SRC:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)

# Compiler settings

CC = i686-elf-gcc
CCFLAGS = -ffreestanding -mno-red-zone -c
CCFLAGS += -Wall -Wextra -Werror -pedantic
HFLAGS = -MMD 

# Linker settings

LD = i686-elf-gcc
LDFLAGS = -r -nostdlib -ffreestanding -lgcc

# Include directories

INCFLAGS = $(foreach TMP, $(LIB_INC_DIR), -I$(TMP))
INCFLAGS += $(foreach TMP, $(INC_DIR), -I$(TMP))

.PHONY: all clean

all: $(MOD_OBJ) 

$(MOD_OBJ): $(OBJ) | $(MOBJ_DIR)
	$(LD) $(OBJ) -o $@ $(LDFLAGS) 

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $< -o $@ $(CCFLAGS) $(HFLAGS) $(INCFLAGS) 

$(OBJ_DIR) $(MOBJ_DIR):
	mkdir -p $@

clean:
	@$(RM) -rv $(OBJ_DIR) $(MOBJ_DIR) 

-include $(OBJ:.o=.d)
